version: "3.7"


networks:
  # backend:
  somenetwork:


volumes:
  volume_vscode-extensions:


services:
  goenv:
    build:
      context: "."
      dockerfile: ./build/build-image/Dockerfile
      target: dev
    cap_add:
      # - ALL
      - SYS_PTRACE
    # cap_drop:
    #   - NET_ADMIN
    #   - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    #   - label:user:USER
    #   - label:role:ROLE
    networks:
      somenetwork:
        aliases:
          - alias1${FOO}
          - alias3
    ports:
      - "27080:27080"
      - "27443:27443"
    working_dir: /workspace
    volumes:
      - .:/workspace
      # - ./.vscode/extensions:/home/vscode/.vscode-server/extensions
      - volume_vscode-extensions:/home/vscode/.vscode-server/extensions
    entrypoint:
      - /bin/entrypoint.dev.sh
      # - sleep
      # - infinity
      # - while :; do sleep 2073600; done

